const API=location.origin;let token=localStorage.getItem('d2h_token')||'',me=null,channel=null,stream=null,screenStream=null,pc=null,publishSession=null,socket=null,live=false;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function api(path,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};return fetch(API+path,opts)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
async function init(){if(!token)return;let r=await api('/api/auth/me');if(!r.ok)return;$('authGate').hidden=true;$('studioApp').hidden=false;me=(await r.json()).user;await loadChannel();await devices();}
async function loadChannel(){let r=await api('/api/profile/channel');if(r.status===404){channel=null;$('channelSlug').textContent='Канал ещё не создан';return}if(!r.ok){toast('Не удалось загрузить канал');return}channel=(await r.json()).channel;if(!channel){$('channelSlug').textContent='Канал ещё не создан';return}setChannelUI();await loadModerators();await loadBans();}
function setChannelUI(){ $('channelSlug').textContent='@'+channel.slug;$('title').value=channel.title||'';$('description').value=channel.description||'';$('category').value=channel.category||'ranked';$('statSubs').textContent=(channel.subscriberCount||0).toLocaleString('ru-RU');$('statStatus').textContent=channel.live?'LIVE':'OFFLINE';$('statusBadge').textContent=channel.live?'● LIVE':'● OFFLINE';$('statusBadge').style.color=channel.live?'#5ee28b':'#ff6b5c';$('statViewers').textContent='0';$('whipUrl').textContent=channel.urls?.whip||'—';$('rtmpUrl').textContent=window.__streamKey&&channel.urls?.rtmp?`${channel.urls.rtmp}?user=${encodeURIComponent(channel.slug)}&pass=${encodeURIComponent(window.__streamKey)}`:'—'}
async function devices(){let list=await navigator.mediaDevices.enumerateDevices();fill('camera',list.filter(x=>x.kind==='videoinput'),'Камера');fill('mic',list.filter(x=>x.kind==='audioinput'),'Микрофон');}
function fill(id,arr,empty){$(id).innerHTML=arr.length?arr.map((x,i)=>`<option value="${esc(x.deviceId)}">${esc(x.label||empty+' '+(i+1))}</option>`).join(''):`<option value="">Нет устройств</option>`}
async function startPreview(){try{stopTracks(false);const [w,h]=($('quality').value).split('x').map(Number);stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:$('camera').value?{exact:$('camera').value}:undefined,width:{ideal:w},height:{ideal:h},frameRate:{ideal:30}},audio:{deviceId:$('mic').value?{exact:$('mic').value}:undefined,echoCancellation:true,noiseSuppression:true}});$('preview').srcObject=stream;$('previewEmpty').style.display='none';$('previewLive').style.display='block';$('previewBtn').textContent='↻ Перезапустить предпросмотр';await devices();toast('Предпросмотр запущен')}catch(e){toast('Нет доступа к камере/микрофону: '+e.message)}}
function stopTracks(all=true){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(screenStream){screenStream.getTracks().forEach(t=>t.stop());screenStream=null}if(all){$('preview').srcObject=null;$('previewEmpty').style.display='grid';$('previewLive').style.display='none'}}
async function toggleScreen(){try{if(screenStream){screenStream.getTracks().forEach(t=>t.stop());screenStream=null;return startPreview()}screenStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const audio=stream?.getAudioTracks()[0];const tracks=[screenStream.getVideoTracks()[0],...(audio?[audio]:screenStream.getAudioTracks())];stream=new MediaStream(tracks);$('preview').srcObject=stream;$('previewEmpty').style.display='none';$('previewMode').textContent='Захват экрана';screenStream.getVideoTracks()[0].onended=()=>startPreview()}catch(e){toast('Захват экрана отменён')}}
async function publish(){if(!channel){toast('Сначала создай канал в настройках');return}if(!stream){await startPreview();if(!stream)return}try{const url=new URL(channel.urls.whip);url.searchParams.set('token',await getKey());pc=new RTCPeerConnection({iceServers:await iceServers()});stream.getTracks().forEach(t=>pc.addTrack(t,stream));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/sdp'},body:pc.localDescription.sdp});if(!res.ok)throw new Error('WHIP '+res.status);const answer=await res.text();await pc.setRemoteDescription({type:'answer',sdp:answer});live=true;await setLive(true);$('stopBtn').disabled=false;$('goLiveBtn').disabled=true;$('statStatus').textContent='LIVE';$('statusBadge').textContent='● LIVE';$('publishInfo').textContent='Эфир запущен через браузер/WebRTC. Для OBS используй WHIP или RTMP.';toast('Эфир запущен')}catch(e){toast('Не удалось начать эфир: '+e.message);if(pc){pc.close();pc=null}}}
async function getKey(){if(window.__streamKey)return window.__streamKey;const r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/rotate-key',{method:'POST'});if(!r.ok)throw new Error('Не удалось получить stream key');const d=await r.json();window.__streamKey=d.streamKey;$('streamKey').textContent=d.streamKey;if(channel.urls?.rtmp)$('rtmpUrl').textContent=`${channel.urls.rtmp}?user=${encodeURIComponent(channel.slug)}&pass=${encodeURIComponent(d.streamKey)}`;return d.streamKey}
async function iceServers(){try{const r=await api('/api/stream/ice');const d=await r.json();return d.iceServers||[]}catch{return []}}
function waitIce(pc){return new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);resolve()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(resolve,5000)})}
async function setLive(v){await api('/api/channels/'+encodeURIComponent(channel.slug)+'/live',{method:'POST',body:JSON.stringify({live:v})});channel.live=v}
async function stopLive(){if(pc){pc.close();pc=null}live=false;await setLive(false);$('stopBtn').disabled=true;$('goLiveBtn').disabled=false;$('statStatus').textContent='OFFLINE';$('statusBadge').textContent='● OFFLINE';$('publishInfo').textContent='Эфир завершён.';toast('Эфир завершён')}
async function saveChannel(){if(!channel)return;let r=await api('/api/channels/'+encodeURIComponent(channel.slug),{method:'PUT',body:JSON.stringify({title:$('title').value,description:$('description').value,category:$('category').value})}),d=await r.json();if(!r.ok)return toast(d.error||'Ошибка');channel={...channel,...d.channel};$('saveMsg').textContent='Сохранено';setTimeout(()=>$('saveMsg').textContent='',1800);toast('Настройки сохранены')}
async function createChannel(){let r=await api('/api/channels',{method:'POST',body:JSON.stringify({title:$('title').value||me.username,slug:me.username,description:$('description').value,category:$('category').value})}),d=await r.json();if(!r.ok)return toast(d.error||'Ошибка');channel=d.channel;window.__streamKey=d.streamKey;$('streamKey').textContent=d.streamKey;setChannelUI();toast('Канал создан')}
async function rotateKey(){if(!channel)return createChannel();let r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/rotate-key',{method:'POST'}),d=await r.json();if(r.ok){window.__streamKey=d.streamKey;$('streamKey').textContent=d.streamKey;if(channel.urls?.rtmp)$('rtmpUrl').textContent=`${channel.urls.rtmp}?user=${encodeURIComponent(channel.slug)}&pass=${encodeURIComponent(d.streamKey)}`;toast('Stream key обновлён')}}
async function loadModerators(){if(!channel)return;let r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/moderators');if(!r.ok)return;let d=await r.json();$('modList').innerHTML=(d.moderators||[]).map(x=>`<div class="mod-row"><span>🛡 ${esc(x.username)}</span><button class="follow-btn danger" data-delmod="${esc(x.username)}">×</button></div>`).join('')||'<div class="hint">Модераторов пока нет.</div>'}
async function loadBans(){if(!channel)return;let r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/bans');if(!r.ok)return;let d=await r.json();$('banList').innerHTML=(d.bans||[]).map(x=>`<div class="mod-row"><span>🚫 ${esc(x.username)}</span></div>`).join('')||'<div class="hint">Заблокированных нет.</div>'}
function connectViewers(){if(!channel)return;const proto=location.protocol==='https:'?'wss':'ws';const u=new URLSearchParams({channel:channel.slug,token});socket=new WebSocket(`${proto}://${location.host}/ws?${u}`);socket.onmessage=e=>{let m=JSON.parse(e.data);if(m.type==='presence'){ $('viewerCount').textContent=m.viewers||0;$('statViewers').textContent=m.viewers||0;$('viewerList').innerHTML=(m.users||[]).map(x=>`<div class="viewer online">${esc(x)}</div>`).join('')||'<div class="hint">Никого нет в эфире.</div>'}}}
$('previewBtn').onclick=startPreview;$('screenToggle').onclick=toggleScreen;$('cameraToggle').onclick=startPreview;$('goLiveBtn').onclick=async()=>{if(!channel){return toast('Создай канал через кнопку «Создать канал» ниже')};publish()};$('stopBtn').onclick=stopLive;$('saveChannel').onclick=async()=>channel?saveChannel():createChannel();$('rotateKey').onclick=rotateKey;$('copyKey').onclick=async()=>{if($('streamKey').textContent.includes('•'))return toast('Сначала создай или смени ключ');await navigator.clipboard.writeText($('streamKey').textContent);toast('Ключ скопирован')};$('addMod').onclick=()=>{$('modForm').hidden=!$('modForm').hidden};$('saveMod').onclick=async()=>{let u=$('modUser').value.trim();if(!u||!channel)return;let r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/moderators',{method:'POST',body:JSON.stringify({username:u})});toast(r.ok?'Модератор добавлен':(await r.json()).error||'Ошибка');if(r.ok){$('modUser').value='';loadModerators()}};$('refreshBans').onclick=loadBans;$('modList').onclick=async e=>{let b=e.target.closest('[data-delmod]');if(!b)return;let u=b.dataset.delmod,r=await api('/api/channels/'+encodeURIComponent(channel.slug)+'/moderators/'+encodeURIComponent(u),{method:'DELETE'});if(r.ok)loadModerators()};window.addEventListener('beforeunload',()=>{if(live&&channel){fetch('/api/channels/'+encodeURIComponent(channel.slug)+'/live-beacon',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({live:false}),keepalive:true}).catch(()=>{});}stopTracks()});init().then(connectViewers);
