let liveStreams=[];
let category='all', following=false, liked=false, socket=null, currentChannel=null, me=null, authToken=localStorage.getItem('d2h_token')||'';
const grid=document.getElementById('streamGrid'),empty=document.getElementById('emptyStreams'),count=document.getElementById('streamCount'),modal=document.getElementById('modal');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalizeStream(s){return {...s,channel:s.channel||s.slug,user:s.user||s.username||'Игрок',cat:s.cat||s.category||'ranked',tag:s.tag||'Dota 2',av:s.av||String(s.user||s.username||'D2').slice(0,2).toUpperCase(),viewers:Number(s.viewers||0),live:!!s.live};}
async function loadStreams(){
  try{const r=await fetch('/api/streams');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();liveStreams=(d.streams||[]).map(normalizeStream);}
  catch(e){liveStreams=[];}
  render();
  const q=new URLSearchParams(location.search).get('channel');
  if(q)openChannel(q); else if(liveStreams.length)showPlayer(liveStreams[0]); else showEmptyFeatured();
}
function render(){
  const q=document.getElementById('streamSearch').value.trim().toLowerCase(),sort=document.getElementById('sortStreams').value;
  let list=liveStreams.filter(x=>x.live&&(category==='all'||x.cat===category)&&(`${x.user} ${x.title} ${x.tag}`).toLowerCase().includes(q));
  if(sort==='viewers')list.sort((a,b)=>(b.viewers||0)-(a.viewers||0)); else list.sort((a,b)=>(b.id||0)-(a.id||0));
  count.textContent=`${list.length} ${list.length===1?'трансляция':'трансляций'}`;empty.hidden=!!list.length;['all','pro','ranked','fun'].forEach(cat=>{const el=document.getElementById('cat'+cat[0].toUpperCase()+cat.slice(1)+'Count');if(el)el.textContent=liveStreams.filter(x=>x.live&&(cat==='all'||x.cat===cat)).length});
  grid.innerHTML=list.map((x,i)=>`<article class="stream-card" data-channel="${esc(x.channel)}" data-user="${esc(x.user)}" data-title="${esc(x.title||'')}" data-viewers="${x.viewers||0}"><div class="thumb"><span class="live-pill">● LIVE</span><span class="viewer-count">👁 ${(x.viewers||0).toLocaleString('ru-RU')}</span></div><div class="stream-card-info"><div class="card-user"><div class="mini-avatar">${esc(x.av)}</div><div><strong>${esc(x.user)}</strong><small>Сейчас в эфире</small></div></div><div class="card-title">${esc(x.title||'Без названия')}</div><div class="card-tags">Dota 2 · ${esc(x.tag)}</div></div></article>`).join('');
}
function playerHtml(url){return `<iframe class="stream-frame" src="${esc(url)}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`;}
async function openChannel(channel){
  try{const r=await fetch('/api/streams/'+encodeURIComponent(channel),{headers:authToken?{Authorization:'Bearer '+authToken}:{}});if(!r.ok)throw new Error('HTTP '+r.status);const s=normalizeStream(await r.json());showPlayer(s);connectChat(s.channel);return;}
  catch(e){showEmptyFeatured();disconnectChat();}
}
function showEmptyFeatured(){currentChannel=null;disconnectChat();document.getElementById('featuredPlayer').innerHTML='<div class="player-placeholder"><div class="player-center">▶</div><p>Сейчас нет активных трансляций</p><small>Когда кто-нибудь начнёт эфир, он появится здесь.</small></div>';document.getElementById('featuredViewers').textContent='0';document.querySelector('.streamer-line h2').textContent='Нет активных каналов';document.querySelector('.streamer-line p').textContent='';document.getElementById('followBtn').textContent='＋ Подписаться';document.getElementById('followBtn').disabled=true;}
function showPlayer(s){
  currentChannel=s.channel||s.slug;document.getElementById('followBtn').disabled=false;document.getElementById('featuredPlayer').innerHTML=s.live&&s.urls?.webrtc?playerHtml(s.urls.webrtc):'<div class="player-placeholder"><div class="player-center">OFF</div><p>Канал сейчас не в эфире</p><small>Запусти трансляцию через студию или OBS.</small></div>';
  document.getElementById('featuredViewers').textContent=(s.viewers||0).toLocaleString('ru-RU');document.querySelector('.streamer-line h2').textContent=s.user||s.username||'—';document.querySelector('.streamer-line p').textContent=s.title||'';const tags=document.getElementById('featuredTags');if(tags)tags.innerHTML=[s.category||s.cat,s.tag].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');following=!!s.subscribed;document.getElementById('followBtn').textContent=following?'✓ Вы подписаны':'＋ Подписаться';history.replaceState(null,'',`stream.html?channel=${encodeURIComponent(currentChannel)}`);
}
function openStream(channel){openChannel(channel);document.getElementById('featuredPlayer').scrollIntoView({behavior:'smooth',block:'center'});}
function close(){modal.classList.remove('show');document.getElementById('modalContent').innerHTML='';}
function disconnectChat(){if(socket){socket.close();socket=null;}}
function connectChat(channel){disconnectChat();currentChannel=channel;const proto=location.protocol==='https:'?'wss':'ws';const qs=new URLSearchParams({channel});if(authToken)qs.set('token',authToken);socket=new WebSocket(`${proto}://${location.host}/ws?${qs}`);socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='history'){document.getElementById('chatMessages').innerHTML='';m.messages.forEach(addChat)}if(m.type==='chat')addChat(m.message);if(m.type==='presence')document.getElementById('onlineChat').textContent=Number(m.viewers||0).toLocaleString('ru-RU');}catch{}};}
function addChat(m){const row=document.createElement('div');row.innerHTML=`<b>${esc(m.user)}</b> ${esc(m.text)}`;document.getElementById('chatMessages').appendChild(row);const box=document.getElementById('chatMessages');box.scrollTop=box.scrollHeight;}
function authModal(){document.getElementById('modalContent').innerHTML=`<div class="creator"><div class="eyebrow">ACCOUNT</div><h2>Аккаунт Dota 2 Helper</h2><div class="auth-tabs"><button class="follow-btn" id="loginTab">Войти</button><button class="follow-btn" id="regTab">Регистрация</button></div><div id="authForm"></div></div>`;modal.classList.add('show');renderAuthForm('login');}
function renderAuthForm(mode){document.getElementById('authForm').innerHTML=mode==='login'?`<label>Логин или email<input id="aLogin"></label><label>Пароль<input id="aPass" type="password"></label><button class="btn red" id="authSubmit">Войти</button>`:`<label>Ник<input id="aUser" maxlength="24"></label><label>Email<input id="aEmail" type="email"></label><label>Пароль<input id="aPass" type="password" minlength="8"></label><button class="btn red" id="authSubmit">Создать аккаунт</button>`;document.getElementById('authSubmit').onclick=async()=>{const body=mode==='login'?{login:document.getElementById('aLogin').value,password:document.getElementById('aPass').value}:{username:document.getElementById('aUser').value,email:document.getElementById('aEmail').value,password:document.getElementById('aPass').value};const r=await fetch('/api/auth/'+mode,{method:'POST',body:JSON.stringify(body)}),d=await r.json();if(!r.ok){alert(d.error||'Ошибка');return}authToken=d.token;localStorage.setItem('d2h_token',authToken);localStorage.setItem('d2h_user',JSON.stringify(d.user));me=d.user;modal.classList.remove('show');document.getElementById('authBtn').textContent='👤 '+me.username;loadStreams()};document.getElementById('loginTab').onclick=()=>renderAuthForm('login');document.getElementById('regTab').onclick=()=>renderAuthForm('register');}
async function refreshMe(){if(!authToken)return;const r=await fetch('/api/auth/me',{headers:{Authorization:'Bearer '+authToken}});if(r.ok){me=(await r.json()).user;document.getElementById('authBtn').textContent='👤 '+me.username}else{authToken='';localStorage.removeItem('d2h_token');localStorage.removeItem('d2h_user')}}
async function openCreator(){if(!me){authModal();return}const r=await fetch('/api/profile/channel',{headers:{Authorization:'Bearer '+authToken}});const d=await r.json();const own=d.channel?normalizeStream(d.channel):null;document.getElementById('modalContent').innerHTML=`<div class="creator"><div class="eyebrow">CREATOR STUDIO</div><h2>${own?'Управление каналом':'Создание канала'}</h2>${own?`<p><b>${esc(own.channel)}</b> · ${own.live?'🔴 LIVE':'offline'}</p><label>Новый stream key<input id="streamKey" readonly placeholder="Нажмите ротацию"></label><div class="account-actions"><button class="btn red" id="rotateKey">Сменить stream key</button><button class="follow-btn" id="modSetup">Модератор</button></div><div class="donate-grid"><button class="follow-btn" id="markLive">${own.live?'Остановить':'Запустить'} эфир</button></div>`:`<label>Название<input id="cTitle" value="Мой Dota 2 канал"></label><label>Slug<input id="cSlug" value="${esc(me.username.toLowerCase())}"></label><button class="btn red" id="createChannel">Создать канал</button>`}<div id="studioResult"></div></div>`;modal.classList.add('show');
 if(!own){document.getElementById('createChannel').onclick=async()=>{const r=await fetch('/api/channels',{method:'POST',body:JSON.stringify({title:document.getElementById('cTitle').value,slug:document.getElementById('cSlug').value})}),d=await r.json();document.getElementById('studioResult').innerHTML=r.ok?`<p>Канал создан. <b>Stream key:</b> <code>${esc(d.streamKey)}</code></p><p>Сохрани ключ: он используется OBS/WHIP.</p>`:`<p class="auth-error">${esc(d.error||'Ошибка')}</p>`};return}
 document.getElementById('rotateKey').onclick=async()=>{const r=await fetch('/api/channels/'+encodeURIComponent(own.channel)+'/rotate-key',{method:'POST'}),d=await r.json();document.getElementById('streamKey').value=d.streamKey||d.error||''};document.getElementById('markLive').onclick=async()=>{await fetch('/api/channels/'+encodeURIComponent(own.channel)+'/live',{method:'POST',body:JSON.stringify({live:!own.live})});openCreator();loadStreams()};document.getElementById('modSetup').onclick=()=>{document.getElementById('studioResult').innerHTML='<label>Ник модератора<input id="modUser"></label><button class="btn red" id="addMod">Добавить модератора</button>';document.getElementById('addMod').onclick=async()=>{const r=await fetch('/api/channels/'+encodeURIComponent(own.channel)+'/moderators',{method:'POST',body:JSON.stringify({username:document.getElementById('modUser').value})});document.getElementById('studioResult').textContent=r.ok?'Модератор добавлен.':(await r.json()).error}};
}
document.querySelectorAll('.side-link').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('.side-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();}));document.getElementById('streamSearch').addEventListener('input',render);document.getElementById('sortStreams').addEventListener('change',render);grid.addEventListener('click',e=>{const c=e.target.closest('.stream-card');if(c)location.href='channel.html?channel='+encodeURIComponent(c.dataset.channel)});document.getElementById('close').onclick=close;document.getElementById('modalBg').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});document.getElementById('startStream').onclick=()=>{if(!me){authModal();return}location.href='studio.html'};
document.getElementById('followBtn').onclick=async()=>{if(!currentChannel)return;if(!authToken){location.href='auth.html?next='+encodeURIComponent(location.href);return}try{const r=await fetch('/api/channels/'+encodeURIComponent(currentChannel)+'/subscribe',{method:'POST',body:'{}'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка');following=!!d.subscribed;document.getElementById('followBtn').textContent=following?'✓ Вы подписаны':'＋ Подписаться';}catch(e){alert(e.message)}};
document.getElementById('likeBtn').onclick=()=>{liked=!liked;document.getElementById('likeBtn').textContent=liked?'♥':'♡'};document.getElementById('shareBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);alert('Ссылка на канал скопирована!')}catch{}};document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();const input=document.getElementById('chatInput'),v=input.value.trim();if(!v)return;if(!authToken){location.href='auth.html?next='+encodeURIComponent(location.href);return}if(socket&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'chat',text:v}));input.value='';};
const menuBtn=document.getElementById('menu'),nav=document.getElementById('navMenu');menuBtn.onclick=()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
refreshMe().finally(loadStreams);
